name: Translation Submission
description: Submit a Translation
labels: ["translation"]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to translate this application!
  - type: input
    attributes:
      label: Language
      description: |
        Examples:
        ur_PK: Urdu (Pakistan)
        en_US: English (United States)
        fa: Farsi/Persian
      placeholder: "Language Code: Language Name"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Translation Action
      options:
        - New Translation
        - Update existing Translation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Changes (Optional)
      description: |
        What changes did you make to the translation?

        **Example:**
        - Add translation for new text 
        - Correct incorrect/inappropriate translations
        - Shorten some translations
    validations:
      required: false
  - type: textarea
    attributes:
      label: Translation File
      description: Link-to/contents-of your translation (.po) file
    validations:
      required: true
  - type: input
    attributes:
      label: Author Name
      description: |
        Your full name

        It will be used to identify you as the author of this change.
    validations:
      required: true
  - type: input
    attributes:
      label: Author Email
      description: |
        It will be used to identify you as the author of this change.

        Note: If you want to keep your real email private, you can put your GitHub noreply email here.
    validations:
      required: true
